apiVersion: v1
kind: Service
metadata:
  name: lc-assignment-mongo
spec:
  selector:
    app: lc-assignment-mongo
  ports:
    - port: 27017
      name: lcmongo
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-assignment-mongo
  labels:
    app: lc-assignment-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lc-assignment-mongo
  template:
    metadata:
      labels:
        app: lc-assignment-mongo
    spec:
      containers:
        - name: lc-assignment-mongo
          image: redis:latest
          ports:
            - containerPort: 27017
              name: lcmongo
      volumeMounts:
        - mountPath: /data/db
          name: lc-assignment-mongo-data
      volumes:
        - name: lc-assignment-mongo-data
          persistentVolumeClaim:
          claimName: lc-assignment-mongo-vol

