kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lc-assignment-mongo-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  storageClassName: manual

