apiVersion: v1
kind: Service
metadata:
  name: lc-assignment-backend
spec:
  selector:
    app: lc-assignment-backend
  ports:
    - protocol: TCP
      port: 5013
      targetPort: 5013
      name: tcp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-assignment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lc-assignment-backend
  template:
    metadata:
      labels:
        app: lc-assignment-backend
    spec:
      imagePullSecrets:
        - name: registry-credential
      containers:
        - name: lc-assignment-backend
          image: registry.digitalocean.com/topcode/lc-assignment-backend:latest
          ports:
            - containerPort: 5013
          envFrom:
            - configMapRef:
                name: lc-assignment-backend-config

