apiVersion: v1
kind: Service
metadata:
  name: lc-assignment-redis
spec:
  selector:
    app: lc-assignment-redis
  ports:
    - port: 6379
      name: lcredis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-assignment-redis

  labels:
    app: lc-assignment-redis
spec:
 volumeMounts:
    - mountPath: /data
      name: lc-assignment-redis-data
  volumes:
    - name: lc-assignment-redis-data
      persistentVolumeClaim:
        claimName: lc-assignment-redis-vol
  replicas: 1
  selector:
    matchLabels:
      app: lc-assignment-redis
  template:
    metadata:
      labels:
        app: lc-assignment-redis
    spec:
      containers:
        - name: lc-assignment-redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
              name: lcredis

