apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lc-assignment-ingress
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    # Uncomment once hello.example.com points to the external IP address of the DO load-balancer.
    service.beta.kubernetes.io/do-loadbalancer-hostname: "lc-assignment-backend.topcode.gr"
spec:
  rules:
    - host: lc-assignment-backend.topcode.gr
      http:
        paths:
          - backend:
              service:
                name: lc-assignment-backend
                port:
                  number: 5013

            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - lc-assignment-backend.topcode.gr
      secretName: lc-assignment-backend-tls

