apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: v1

images:
  - name: registry.digitalocean.com/topcode/lc-assignment-backend
    newTag: latest

resources:
  - ../../base
  ##
  - ingress/backend.ingress.yaml
  - configs/backend.cm.yaml
