apiVersion: v1
kind: ConfigMap
metadata:
  name: lc-assignment-backend-config
data:
  PORT: "5013"
  REDIS_HOST: lc-assignment-redis
  REDIS_PORT: "6379"
  MONGODB_URI: mongodb://lc-assignment-mongo:27017/lc-assignment?authSource=admin

